### ISSUE TITLE
Pulling token from env is obscured if using Github app token

### ISSUE THREAD

**Issue by mephmanx** [Justintime50/homebrew-releaser#29]
I use this process to get a github api token for project access in my org:

npx obtain-github-app-installation-access-token

This can get a github PAT for repos but when passing the result of this call into your action, the token is obscured by github as it seems like it crosses a boundry where github detects it and obscures it thus the release fails as it cant update the github repo with the formula.  Can you add something where you could read the token from a file or something?  I usually use /tmp/token

something where this works:

TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GH_TOKEN }} | base64)"
          echo "$TOKEN" >> /tmp/token

then you load that file and read token so that github dosent detect that it is a secure string.

**Comment by Justintime50** [comment]
I'm not sure what the use-case is of this kind of flow? Can you help elaborate or show a code snippet that you use?

Why not just store the GitHub Token in GitHub's Secret Store which is the standard for CI env management?

**Comment by mephmanx** [comment]
There isnt currently a NEED to not generate a token and store it but a very strong desire to not do that.  I would prefer to not need to regenerate tokens after the expiry period and I REALLY do not want to use a non-expiring token.  The app token integration works VERY well for this and has eliminated the need to generate any github PAT tokens so far in my entire project which has over 40 repos and at least 50 bithub workflows.

I guess I could take a look.  After I got the github app token integration working though, I just dont want to use PAT's again.  Saves me from ever forgetting to do a security review.

**Comment by mephmanx** [comment]
The repo is public

https://github.com/dotcomrow/vault-ops-keys

**Comment by Justintime50** [comment]
Anyway you can swap in the version hash of the Homebrew Releaser action to use the draft PR I put up? `489a8f9911a265348cf0a11ab061030971f32278`

I think your workflow should work with this but the error that was actually output couldn't tell that your token was in the password field. Let me know if this works for you and we can merge and release officially if it does the trick.

**Comment by mephmanx** [comment]
ok, Ill try now.  Thank you!

**Comment by mephmanx** [comment]
That worked great, thank you!  Let me know when new latest version is deployed and Ill switch back to that.

**Comment by Justintime50** [comment]
You should be good to go back to `v1` or `v0.16.1` for a more strict pin. Thanks for reporting this issue.

**Comment by mephmanx** [comment]
hmmm...seeing this error when I switched to v1...
<img width="962" alt="Screenshot 2023-03-15 at 5 16 03 PM" src="https://user-images.githubusercontent.com/52037738/225445754-bc72b32a-b476-484d-91ea-cbc198f7a139.png">

**Comment by Justintime50** [comment]
Odd... can you retry the failed build to ensure it wasn't transient?

**Comment by mephmanx** [comment]
ok, Ill retry

**Comment by mephmanx** [comment]
retried build, same error.  seems like it runs but returns a non 0 code...  worked perfectly with the hash version though...

**Comment by Justintime50** [comment]
Do you mind trying the `v0.16.1` version? I wonder if it's just the repackaging of the v1 tag that broke or something else.

**Comment by mephmanx** [comment]
sure, will try now.

**Comment by mephmanx** [comment]
same error unfortunately...
<img width="946" alt="Screenshot 2023-03-15 at 7 54 57 PM" src="https://user-images.githubusercontent.com/52037738/225470084-a5b7513d-f777-408f-bc6e-d19736cf58ae.png">

**Comment by Justintime50** [comment]
Ah, that was enough info to figure out that I forgot to bump the version of the Python app itself which most likely led to this 😭 Wanna try `v1` one last time (released via `v0.16.2`)? Should do the trick now. Let me know what happens.

**Comment by mephmanx** [comment]
ok, will try now. Thx!  I have done that myself so many times...   I love github actions for that now though too, I only release stuff through there and automate it away.

**Comment by mephmanx** [comment]
Actually, that didnt do it either...
<img width="1078" alt="Screenshot 2023-03-15 at 9 51 19 PM" src="https://user-images.githubusercontent.com/52037738/225489227-38e16bff-31ad-4bb6-b50b-d2cf3fcbf2c6.png">

**Comment by Justintime50** [comment]
Ah this error is not related (most likely) to the last item we fixed. Sending a screenshot of the actual error message in the future would be helpful (had to go look in your action logs). 

Investigating this new error now

**Comment by Justintime50** [comment]
I apologize for the back and forth. I have another commit hash that may shine some light on the situation: `c8138fd555022f4341e43c2e82d2c293a09fa5be`. This should open up the errors a bit more and hopefully provide a stack trace and message that will be helpful to know why it's failing at that point. Unfortunately, I tried recreating this myself with your repo (running it locally) and was not met with the same error, it worked fine for me which means I'll need your help to continue troubleshooting.

**Comment by mephmanx** [comment]
ok, will try now.

**Comment by mephmanx** [comment]
<img width="950" alt="Screenshot 2023-03-16 at 7 56 24 AM" src="https://user-images.githubusercontent.com/52037738/225609566-cbd9b411-f739-4d66-b9a3-2215e9f10ed7.png">

**Comment by Justintime50** [comment]
Thanks for your patience on this! We got that stack trace but still not the error message, though I think I figured out why it didn't come through. I'm still unable to replicate your exact issue, but forcing one of my own seems to now be printing out the output of the command failure in addition to the stack trace. If you're able, wanna try `75eb168ec5240e1011b1c0b71fcfd9c6408e543c` and post the output from that?

**Comment by mephmanx** [comment]
sure, latest trace
<img width="984" alt="Screenshot 2023-03-16 at 7 06 23 PM" src="https://user-images.githubusercontent.com/52037738/225771982-f46c38a0-7f39-4c88-92ec-ca0694f2f238.png">

**Comment by Justintime50** [comment]
Ah perfect! I don't think there is anything wrong here. The error is finally exposed and it says your repo is up to date so it can't commit anything. Because all you did was change the hash of the action (and the version of the homebrew formula didn't actually change so the formula file wasn't regenerated) there is nothing to commit so it fails and exits. If we were to cut a new release, this should work just fine.

Hope that helps! I think I'll push up the error handling fixes you helped me discover so they're there for future travelers, but as far as the actual issue on this ticket, I believe it's solved. I would change your release workflow to only trigger on a release instead of each commit since it requires a new release to pass anyway. An alternative if you want to continue dry runs is to use the `skip_commit` flag.

**Comment by Justintime50** [comment]
Thanks for your help debugging this! I've released `v0.16.3` and `v1` is repackaged with these changes.

For your use-case, things should start working again once you cut a new release of your own project.

**Comment by mephmanx** [comment]
I changed from using the hash version to v1 and I still get this error...
![Screenshot 2023-03-17 at 7 48 20 AM](https://user-images.githubusercontent.com/52037738/225896446-ca85f3d3-4479-40b6-af9c-30bd5f49eb18.png)

**Comment by mephmanx** [comment]
I tried 0.16.3,0.16.1,0.16.0, none of them build my project anymore now...

**Comment by Justintime50** [comment]
As mentioned above, for this to work, you will need to cut a new release of your project: https://github.com/dotcomrow/vault-ops-keys/releases/new.

The reason it's not working for you is that the generated formula does not differ than what is already there so when it tries to commit, as you can see in your 2nd to last screenshot, it says "your branch is up to date, nothing to commit" and fails. For there to be something to commit (and for it to ultimately succeed), the version of your package needs to change so the formula will differ which will allow git to track and commit those changes.

Also, you need to adjust your workflow to only trigger on releases per the docs. You are currently having it trigger on any change which will lead to failures since not every commit you make will correlate with a release. Change https://github.com/dotcomrow/vault-ops-keys/blob/f789f2dc7cd1b89b977434de3818c6fdec967a65/.github/workflows/publish-brew.yml#L5-L7 to the following:

```yaml
on:
  release:
    types: [published]
```

**Comment by mephmanx** [comment]
Ok, I will try.  I do actually want it to build/tag/release/and publish on every change.  I am the only one who commits to this so it is set up intentionally made that way.

**Comment by Justintime50** [comment]
- [ ] Ok, if that is the case, you will want to automate a release on every commit. Homebrew Releaser only works with releases, not individual commits.

**Comment by mephmanx** [comment]
I have tried setting this up a bunch of ways but I keep getting errors...Im getting the autogenerated checksum error again...no matter which version I use v1, v0.16.0, v.0.16.3, nothing works now...  I know a release and tag are being created...

**Comment by Justintime50** [comment]
Interesting, I've pushed a patch via `v0.16.4`, let me know if that fixes things for you.

**Comment by mephmanx** [comment]
ok, thanks.  let me try.

**Comment by mephmanx** [comment]
no success yet...
![Screenshot 2023-03-21 at 8 40 04 AM](https://user-images.githubusercontent.com/52037738/226608749-82ea772e-1918-448e-ae26-8662c9bc0e88.png)

**Comment by Justintime50** [comment]
Dang, I can't recreate this (yet) myself. I created a new issue to track this since this issue is different than the original one reported. Let's continue this conversation there.
